### ISSUE TITLE
Login doesn't seem to check password when given an invalid account, returns 200 & chatroom info

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#1]
The request returns immediately, signifying that the password isn't check against anything. I'm not sure, but I think this might have been added when chatroom info was added to /login/.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Hi,
I wont be able to look into this for you till next week, but thank you for your submission :)

**Comment by bczsalba** [comment]
brother it is next week

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
I mean I commented that on the 15th of march (this week). which broadly means that **next** week will be in 7 days :)

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
bug has been fixed. 
It was due to a temporary fix that I set up so you could get the chatname when logging in
