### ISSUE TITLE
(Potential) Fix namespacing inconsistencies

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#6]
This is a bit nitpicky, but we could be more strict about variable naming conventions. Most of the server uses `snake_case`, but some use `camelCase` (like `inviteData`), while some others like `inviteID` and `chatroomID` use something else completely.

Examples for proposed change:
`inviteData` -> `invite_data`
`inviteID` -> `invite_id`

This would in general improve code quality, and would aid in potential future contributors keeping style guides.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Variable name consistency is an area which I am not good at.

The default for teahaz-server is snake case but HTTP does not allow the character `_` in headers so IDs were originally camel. Then later I ended up changing all IDs to having the `ID` caps to signify to myself that that has to be a UUID and should crash if it isnt.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
I think overall this naming scheme is not perfect and Ill try get better at it. Thanks for feedback :slightly_smiling_face:

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
I have added a fix to my todo.md file, but it will probably be a while till I can get to this.

![Screenshot from 2021-07-05 13-40-01](https://user-images.githubusercontent.com/46561460/124472876-edda2580-dd9e-11eb-87e5-85018a46c2d9.png)

**Comment by bczsalba** [comment]
Thanks bruv :rocket:
