### ISSUE TITLE
Make `/messages/` `POST` return the message object

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#7]
Currently, this method returns the message's ID, which complicates things a lot. On message send, it would be a logical thing to call the new-message method for a client loop, which would take in the message context. This would allow client-programs to instantly display sent messages, which makes the experience a lot smoother.

To achieve this with the current systems, one has to send a message, then use either get method, and either blissfully hope it will be the message the user just sent, or loop until it's found. This process is either very bug-friendly, or server resource/user time intensive, with basically no in-between.

The proposed change would have `/messages/` `POST` return data such as:
```python3
{
    "messageID": "a1222cac-ddb1-11eb-b983-60030898377c",
    "channelID": "aeierdf42c-ddb1-11eb-b983-60030898377c"
    "userID": "a1222cac-ddb1-11eb-b983-60030898377c"
    "keyID": "a1222cac-ddb1-11eb-b983-60030898377c"
    "send_time": "1625504010.3218272"
    "type": "text",
    "data": "hello github issue #7!"
}
```

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Great idea! Ill get to it soon.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Done!

Send_message now uses the exact same function to format messages as get does!
